version: "3.8"

services:
  mongodb:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  backend:
    build: .
    restart: always
    environment:
      MONGO_URI: mongodb://mongodb:27017/users
    ports:
      - 3000:3000
    depends_on:
      - mongodb
